import { Branch, Clg, PrismaClient, Role } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Student data structure
interface StudentData {
  serialNo: number;
  alternateId?: string;
  rollNo: string;
  firstName: string;
  lastName?: string;
  email?: string;
  section: string;
  phone?: string;
}

// Section configuration
interface SectionConfig {
  programCode: string; // e.g., "CSE"
  programName: string; // e.g., "Computer Science and Engineering"
  sectionName: string; // e.g., "A", "B", "C"
  semester: number; // e.g., 3
  batchYear: number; // e.g., 2024
  departmentCode?: string; // e.g., "CSE" (defaults to "CSE")
  departmentName?: string; // e.g., "Computer Science and Engineering"
}

// Default values
const DEFAULT_PASSWORD = "0123456789";
const DEFAULT_COLLEGE: Clg = "MRU";
const DEFAULT_BRANCH: Branch = "SCHOOL_OF_ENGINEERING";

async function seedStudents(
  sectionConfig: SectionConfig,
  studentsData: StudentData[]
) {
  console.log("\n🎓 Starting student seeding process...\n");
  console.log("📋 Configuration:");
  console.log(
    `   Program: ${sectionConfig.programName} (${sectionConfig.programCode})`
  );
  console.log(`   Section: ${sectionConfig.sectionName}`);
  console.log(`   Semester: ${sectionConfig.semester}`);
  console.log(`   Batch Year: ${sectionConfig.batchYear}`);
  console.log(`   Total Students: ${studentsData.length}\n`);

  // 1. Get or create Department
  console.log("🏢 Setting up department...");
  const departmentCode = sectionConfig.departmentCode || "CSE";
  const departmentName =
    sectionConfig.departmentName || "Computer Science and Engineering";

  let department = await prisma.department.findUnique({
    where: { code: departmentCode },
  });

  if (!department) {
    department = await prisma.department.create({
      data: {
        name: departmentName,
        code: departmentCode,
      },
    });
    console.log(`   ✅ Created department: ${departmentName}`);
  } else {
    console.log(`   ✅ Using existing department: ${departmentName}`);
  }

  // 2. Get or create Program
  console.log("📚 Setting up program...");
  let program = await prisma.program.findFirst({
    where: {
      code: sectionConfig.programCode,
      departmentId: department.id,
    },
  });

  if (!program) {
    program = await prisma.program.create({
      data: {
        name: sectionConfig.programName,
        code: sectionConfig.programCode,
        departmentId: department.id,
      },
    });
    console.log(`   ✅ Created program: ${sectionConfig.programName}`);
  } else {
    console.log(`   ✅ Using existing program: ${sectionConfig.programName}`);
  }

  // 3. Get or create Batch
  console.log("📅 Setting up batch...");
  let batch = await prisma.batch.findFirst({
    where: {
      year: sectionConfig.batchYear,
      programId: program.id,
    },
  });

  if (!batch) {
    batch = await prisma.batch.create({
      data: {
        year: sectionConfig.batchYear,
        programId: program.id,
      },
    });
    console.log(`   ✅ Created batch: ${sectionConfig.batchYear}`);
  } else {
    console.log(`   ✅ Using existing batch: ${sectionConfig.batchYear}`);
  }

  // 4. Get or create Section
  console.log("🏫 Setting up section...");
  let section = await prisma.section.findFirst({
    where: {
      name: sectionConfig.sectionName,
      batchId: batch.id,
      semester: sectionConfig.semester,
    },
  });

  if (!section) {
    section = await prisma.section.create({
      data: {
        name: sectionConfig.sectionName,
        batchId: batch.id,
        semester: sectionConfig.semester,
      },
    });
    console.log(`   ✅ Created section: ${sectionConfig.sectionName}`);
  } else {
    console.log(`   ✅ Using existing section: ${sectionConfig.sectionName}`);
  }

  // 5. Get or create Group G1
  console.log("👥 Setting up group...");
  let group = await prisma.group.findFirst({
    where: {
      name: "G1",
      sectionId: section.id,
    },
  });

  if (!group) {
    group = await prisma.group.create({
      data: {
        name: "G1",
        sectionId: section.id,
      },
    });
    console.log(`   ✅ Created group: G1`);
  } else {
    console.log(`   ✅ Using existing group: G1`);
  }

  // 6. Create students
  console.log("\n👨‍🎓 Creating students...\n");
  const hashedPassword = await bcrypt.hash(DEFAULT_PASSWORD, 10);
  let createdCount = 0;
  let skippedCount = 0;

  for (const studentData of studentsData) {
    const existingStudent = await prisma.user.findUnique({
      where: { rollNo: studentData.rollNo },
    });

    if (existingStudent) {
      console.log(
        `   ⚠️  Skipped: ${studentData.rollNo} - ${studentData.firstName} (already exists)`
      );
      skippedCount++;
      continue;
    }

    const fullName = studentData.lastName
      ? `${studentData.firstName} ${studentData.lastName}`.trim()
      : studentData.firstName;

    const phone =
      studentData.phone ||
      `98${Math.floor(10000000 + Math.random() * 90000000)}`;

    await prisma.user.create({
      data: {
        name: fullName,
        rollNo: studentData.rollNo,
        password: hashedPassword,
        phone: phone,
        email: studentData.email || undefined,
        clg: DEFAULT_COLLEGE,
        branch: DEFAULT_BRANCH,
        role: "STUDENT" as Role,
        sectionId: section.id,
        groupId: group.id,
      },
    });

    console.log(`   ✅ Created: ${studentData.rollNo} - ${fullName}`);
    createdCount++;
  }

  // Summary
  console.log("\n📊 SEEDING SUMMARY FOR SECTION", sectionConfig.sectionName);
  console.log("=".repeat(60));
  console.log(
    `Section: ${sectionConfig.programCode} - ${sectionConfig.sectionName} (Semester ${sectionConfig.semester})`
  );
  console.log(`Total Students in Data: ${studentsData.length}`);
  console.log(`Successfully Created: ${createdCount}`);
  console.log(`Skipped (Already Exists): ${skippedCount}`);
  console.log("=".repeat(60));
}

async function main() {
  // --- Section A Configuration and Data ---
  const sectionAConfig: SectionConfig = {
    programCode: "CSE",
    programName: "Computer Science and Engineering",
    sectionName: "A",
    semester: 3,
    batchYear: 2024,
  };
  const studentsA: StudentData[] = [
    {
      serialNo: 1,
      alternateId: "224101001122",
      rollNo: "2K24CSUN01002",
      firstName: "AAYUSH DUBEY",
      lastName: "MUKESH",
      email: "ayushdubey00067@gmail.com",
      section: "A",
    },
    {
      serialNo: 2,
      alternateId: "22410100139",
      rollNo: "2K24CSUN01003",
      firstName: "ADITYA VATS",
      lastName: "PARMOD KUMAR SHARMA",
      email: "adityavats2006@gmail.com",
      section: "A",
    },
    {
      serialNo: 3,
      alternateId: "22410100169",
      rollNo: "2K24CSUN01004",
      firstName: "AKSHAT VERMA",
      lastName: "SUBHASH VERMA",
      email: "subhashdangi@gmail.com",
      section: "A",
    },
    {
      serialNo: 7,
      alternateId: "224101001156",
      rollNo: "2K24CSUN01007",
      firstName: "ANSHIKA OBEROI",
      lastName: "RAJIV OBEROI",
      email: "oberoipreeti1994@gmail.com",
      section: "A",
    },
    {
      serialNo: 8,
      alternateId: "224101001143",
      rollNo: "2K24CSUN01008",
      firstName: "ANUPAM KUMAR",
      lastName: "AKHILESH KUMAR PRASAD",
      email: "anupamkr0904@gmail.com",
      section: "A",
    },
    {
      serialNo: 9,
      alternateId: "224101001130",
      rollNo: "2K24CSUN01009",
      firstName: "ANUSHKA GARG",
      lastName: "DILIP GARG",
      email: "garg19anushka@gmail.com",
      section: "A",
    },
    {
      serialNo: 10,
      alternateId: "2241010013",
      rollNo: "2K24CSUN01010",
      firstName: "ASHOK NAGPAL",
      lastName: "SHRI RAM NAGPAL",
      email: "shrinagpal09@gmail.com",
      section: "A",
    },
    {
      serialNo: 11,
      alternateId: "22410100112",
      rollNo: "2K24CSUN01011",
      firstName: "AYUSH KUMAR",
      lastName: "ANIL KUMAR",
      email: "indu2635@gmail.com",
      section: "A",
    },
    {
      serialNo: 12,
      alternateId: "224101001127",
      rollNo: "2K24CSUN01012",
      firstName: "BHOOMIKA SHARMA",
      lastName: "RAGHUNANDAN SHARMA",
      email: "bhoomi2060@gmail.com",
      section: "A",
    },
    {
      serialNo: 13,
      alternateId: "22410100150",
      rollNo: "2K24CSUN01013",
      firstName: "BORA SHIVA PRASAD",
      lastName: "BORA BAJANNA",
      email: "borapranavi@gmail.com",
      section: "A",
    },
    {
      serialNo: 14,
      alternateId: "224101001134",
      rollNo: "2K24CSUN01014",
      firstName: "CHETAN SHARMA",
      lastName: "BHAGWAT DAYAL",
      email: "chetanbhardwaj240@gmail.com",
      section: "A",
    },
    {
      serialNo: 15,
      alternateId: "224101001208",
      rollNo: "2K24CSUN01015",
      firstName: "CHETANYA HANS",
      lastName: "SAURABH HANS",
      email: "chetanyahans@gmail.com",
      section: "A",
    },
    {
      serialNo: 16,
      alternateId: "224101001128",
      rollNo: "2K24CSUN01016",
      firstName: "CHIRAG SOOD",
      lastName: "MADHUKAR SOOD",
      email: "chiragsood25@gmail.com",
      section: "A",
    },
    {
      serialNo: 17,
      alternateId: "224101001212",
      rollNo: "2K24CSUN01017",
      firstName: "DAIWIK BHARDWAJ",
      lastName: "ARUN SHARMA",
      email: "arun.ku.sharma@gmail.com",
      section: "A",
    },
    {
      serialNo: 19,
      alternateId: "224101001168",
      rollNo: "2K24CSUN01019",
      firstName: "DRASHTEE SINGH CHAUHAN",
      lastName: "PANKAJ SINGH",
      email: "drashteechauhan@gmail.com",
      section: "A",
    },
    {
      serialNo: 20,
      alternateId: "224101001177",
      rollNo: "2K24CSUN01020",
      firstName: "DUGGEMPUDI MANIKANTA",
      lastName: "DUGGEMPUDI VENKATA RAMAIAH",
      email: "manikantaduggempudi@gmail.com",
      section: "A",
    },
    {
      serialNo: 21,
      alternateId: "22410100149",
      rollNo: "2K24CSUN01021",
      firstName: "GAURAV",
      lastName: "MAMCHAND",
      email: "gouravjangra8305@gmail.com",
      section: "A",
    },
    {
      serialNo: 22,
      alternateId: "224101001121",
      rollNo: "2K24CSUN01022",
      firstName: "GOLLA BRAMESH",
      lastName: "GOLLA VENKATESH",
      email: "brammeshg@gmail.com",
      section: "A",
    },
    {
      serialNo: 23,
      alternateId: "22410100199",
      rollNo: "2K24CSUN01023",
      firstName: "GUBBALA THRIKSHAN SRI SAI",
      lastName: "RAMCHANDRA SHETTY",
      email: "gubblathirkshant@gmail.com",
      section: "A",
    },
    {
      serialNo: 24,
      alternateId: "224101001111",
      rollNo: "2K24CSUN01025",
      firstName: "HARSHEEN KAUR",
      lastName: "DEVINDER SINGH",
      email: "kaurharsheen2017@gmail.com",
      section: "A",
    },
    {
      serialNo: 25,
      alternateId: "224101001189",
      rollNo: "2K24CSUN01026",
      firstName: "HARSHIT SAREEN",
      lastName: "BRIJESH SAREEN",
      email: "sareenharshit7@gmail.com",
      section: "A",
    },
    {
      serialNo: 26,
      alternateId: "224101001120",
      rollNo: "2K24CSUN01027",
      firstName: "HARSHIT YADAV",
      lastName: "MUKESH YADAV",
      email: "meenayadav6t@gmail.com",
      section: "A",
    },
    {
      serialNo: 27,
      alternateId: "22410100142",
      rollNo: "2K24CSUN01028",
      firstName: "HEMANT SHARMA",
      lastName: "RAM BABU SHARMA",
      email: "rajeshs9540@gmail.com",
      section: "A",
    },
    {
      serialNo: 29,
      alternateId: "22410100159",
      rollNo: "2K24CSUN01030",
      firstName: "JAI KISHAN SAINI",
      lastName: "MAHAVIR PRASAD SAINI",
      email: "kapil1360179@gmail.com",
      section: "A",
    },
    {
      serialNo: 30,
      alternateId: "224101001142",
      rollNo: "2K24CSUN01031",
      firstName: "JATIN SOLANKI",
      lastName: "RAJIV THAKUR",
      email: "rajivthakur1780@gmail.com",
      section: "A",
    },
    {
      serialNo: 31,
      alternateId: "224101001221",
      rollNo: "2K24CSUN01032",
      firstName: "KAJAL KUMARI",
      lastName: "SANJAY KUMAR",
      email: "kajal.ks796@gmail.com",
      section: "A",
    },
    {
      serialNo: 32,
      alternateId: "224101001116",
      rollNo: "2K24CSUN01033",
      firstName: "KAVYANSH KAUSHIK",
      lastName: "MIRGENDER KUMAR",
      email: "mirgender@gmail.com",
      section: "A",
    },
    {
      serialNo: 33,
      alternateId: "224101018N9",
      rollNo: "2K24CSUN01034",
      firstName: "KESHAV GOEL",
      lastName: "RUPAL GOEL",
      email: "goelsanjul00@gmail.com",
      section: "A",
    },
    {
      serialNo: 36,
      alternateId: "22410100155",
      rollNo: "2K24CSUN01037",
      firstName: "KRITIKA",
      lastName: "RAJESH KUMAR",
      email: "chhabrakritika541@gmail.com",
      section: "A",
    },
    {
      serialNo: 37,
      alternateId: "22410100122",
      rollNo: "2K24CSUN01038",
      firstName: "KUNAL CHAUHAN",
      lastName: "OMVIR SINGH",
      email: "kunal75chauhan@gmail.com",
      section: "A",
    },
    {
      serialNo: 38,
      alternateId: "224101001124",
      rollNo: "2K24CSUN01039",
      firstName: "MAYANK",
      lastName: "ASHOK KUMAR",
      email: "mayankparjapati959@gmail.com",
      section: "A",
    },
    {
      serialNo: 39,
      alternateId: "224101001172",
      rollNo: "2K24CSUN01040",
      firstName: "MAYANK NEGI",
      lastName: "KAMAL NEGI",
      email: "mayanknegi118@gmail.com",
      section: "A",
    },
    {
      serialNo: 40,
      alternateId: "224101001103",
      rollNo: "2K24CSUN01041",
      firstName: "NALLURI GEETHA MANASWINI",
      lastName: "NALLURI MURALI MOHAN",
      email: "manunalluri76@gmail.com",
      section: "A",
    },
    {
      serialNo: 41,
      alternateId: "224101001153",
      rollNo: "2K24CSUN01042",
      firstName: "NANCY",
      lastName: "RAM AVTAR",
      email: "nancymangla2006@gmail.com",
      section: "A",
    },
    {
      serialNo: 42,
      alternateId: "22410100132",
      rollNo: "2K24CSUN01043",
      firstName: "NANDINI CHAUHAN",
      lastName: "MAN MOHAN SINGH",
      email: "cnandini656@gmail.com",
      section: "A",
    },
    {
      serialNo: 43,
      alternateId: "224101001147",
      rollNo: "2K24CSUN01044",
      firstName: "NEHA GUPTA",
      lastName: "NIRMAL KUMAR GUPTA",
      email: "nehag0864@gmail.com",
      section: "A",
    },
    {
      serialNo: 44,
      alternateId: "224101001170",
      rollNo: "2K24CSUN01045",
      firstName: "NIKHIL KUNTAL",
      lastName: "GIRVAR SINGH",
      email: "nhilkunt@gmail.com",
      section: "A",
    },
    {
      serialNo: 45,
      alternateId: "22410100170",
      rollNo: "2K24CSUN01046",
      firstName: "NIRVIKALP AGRAWAL",
      lastName: "ANURAG AGRAWAL",
      email: "bhavyaagrawal602@gmail.com",
      section: "A",
    },
    {
      serialNo: 47,
      alternateId: "22410100186",
      rollNo: "2K24CSUN01048",
      firstName: "NUKALA MAHESH",
      lastName: "NUKALA YADAGIRI",
      email: "mnukala83@gmail.com",
      section: "A",
    },
    {
      serialNo: 49,
      alternateId: "22410100141",
      rollNo: "2K24CSUN01050",
      firstName: "PARTH PARMAR",
      lastName: "BHANU PRATAP SINGH",
      email: "parthparmar336699@gmail.com",
      section: "A",
    },
    {
      serialNo: 51,
      alternateId: "22410100134",
      rollNo: "2K24CSUN01052",
      firstName: "POTU RANADHEER",
      lastName: "POTU TIRUPATHI",
      email: "ranadheerpotuwar@gmail.com",
      section: "A",
    },
    {
      serialNo: 52,
      alternateId: "22410100120",
      rollNo: "2K24CSUN01053",
      firstName: "PRABAL PRATAP SINGH",
      lastName: "DEEPAK SINGH",
      email: "prabalpratapsingst.johns@gmail.com",
      section: "A",
    },
    {
      serialNo: 54,
      alternateId: "22410100119",
      rollNo: "2K24CSUN01055",
      firstName: "PRINCE RAWAT",
      lastName: "DEVENDER KUMAR",
      email: "princerawat1979@gmail.com",
      section: "A",
    },
    {
      serialNo: 55,
      alternateId: "224101001129",
      rollNo: "2K24CSUN01056",
      firstName: "RENU TEWATIA",
      lastName: "YOGESH TEWATIA",
      email: "tewatiarenu06@gmail.com",
      section: "A",
    },
    {
      serialNo: 56,
      alternateId: "22410100118",
      rollNo: "2K24CSUN01057",
      firstName: "RISHI VERMA",
      lastName: "SANJEEV KUMAR",
      email: "rishi.vr2006@gmail.com",
      section: "A",
    },
    {
      serialNo: 57,
      alternateId: "224101001123",
      rollNo: "2K24CSUN01058",
      firstName: "RIYA MAHTO",
      lastName: "LATE SURESH MAHTO",
      email: "riyamahto2006@gmail.com",
      section: "A",
    },
    {
      serialNo: 58,
      alternateId: "22410100163",
      rollNo: "2K24CSUN01059",
      firstName: "RUDRANSH SINGH",
      lastName: "ANKUSH SINGH",
      email: "rudranshsinghfbd@gmail.com",
      section: "A",
    },
    {
      serialNo: 59,
      alternateId: "22410100195",
      rollNo: "2K24CSUN01060",
      firstName: "SAKSHI SHARMA",
      lastName: "LAVNEET SHARMA",
      email: "sakshisharma59305@gmail.com",
      section: "A",
    },
    {
      serialNo: 60,
      alternateId: "22401001N0",
      rollNo: "2K24CSUN01062",
      firstName: "SHAKTI SINGH KRISHNA KUMAR",
      lastName: "RAMESHWAR SINGH",
      email: "shakti70469@gmail.com",
      section: "A",
    },
    {
      serialNo: 61,
      alternateId: "22410100167",
      rollNo: "2K24CSUN01063",
      firstName: "SHASHANK DUBEY",
      lastName: "VARUNENDRA KUMAR DUBEY",
      email: "shashankdubey0158@gmail.com",
      section: "A",
    },
    {
      serialNo: 63,
      alternateId: "22410100116",
      rollNo: "2K24CSUN01065",
      firstName: "SIYA BHARDWAJ",
      lastName: "NEERAJ BHARDWAJ",
      email: "siyabhardwaj2006@gmail.com",
      section: "A",
    },
    {
      serialNo: 64,
      alternateId: "22410100165",
      rollNo: "2K24CSUN01066",
      firstName: "VADIKARI PREM CHAND",
      lastName: "VADIKARI CHANDER RAO",
      email: "chandgopi7601@gmail.com",
      section: "A",
    },
    {
      serialNo: 67,
      alternateId: "22401001N2",
      rollNo: "2K24CSUN01069",
      firstName: "VINEET KUMAR VINEET",
      lastName: "VINOD SINGH",
      email: "vinodsingh271204@gmail.com",
      section: "A",
    },
    {
      serialNo: 69,
      alternateId: "22410100131",
      rollNo: "2K24CSUN01071",
      firstName: "YASH CHAUHAN",
      lastName: "SUSHIL CHAUHAN",
      email: "yash0620chauhan@gmail.com",
      section: "A",
    },
    {
      serialNo: 70,
      alternateId: "22410100174",
      rollNo: "2K24CSUN01072",
      firstName: "YAVISH UPMANYU",
      lastName: "MUKESH UPMANYU",
      email: "yavishupmanyu6@gmail.com",
      section: "A",
    },
    {
      serialNo: 208,
      alternateId: "22501001L025",
      rollNo: "2K25CSUL01007",
      firstName: "ABHISHEK PUNYANI",
      lastName: "CHANDER MOHAN PUNYANI",
      email: "abhishek.punyani@gmail.com",
      section: "A",
    },
    {
      serialNo: 211,
      alternateId: "22501001L028",
      rollNo: "2K25CSUL01011",
      firstName: "RISHIT RAJ",
      lastName: "RAJAN SAHAY",
      email: "rishitraj0905@gmail.com",
      section: "A",
    },
  ];
  await seedStudents(sectionAConfig, studentsA);

  // --- Section B Configuration and Data ---
  const sectionBConfig: SectionConfig = {
    programCode: "CSE",
    programName: "Computer Science and Engineering",
    sectionName: "B",
    semester: 3,
    batchYear: 2024,
  };
  const studentsB: StudentData[] = [
    {
      serialNo: 72,
      alternateId: "224101001179",
      rollNo: "2K24CSUN01075",
      firstName: "AKSHAT SHARMA",
      lastName: "UPENNDRA SHARMA",
      email: "akshatsh001@gmail.com",
      section: "B",
    },
    {
      serialNo: 73,
      alternateId: "22410100161",
      rollNo: "2K24CSUN01076",
      firstName: "AKSHITA AHUJA",
      lastName: "SUBHASH AHUJA",
      email: "akshitaahuja0706@gmail.com",
      section: "B",
    },
    {
      serialNo: 75,
      alternateId: "224101001161",
      rollNo: "2K24CSUN01078",
      firstName: "ANSH YADAV",
      lastName: "ASHBIR SINGH",
      email: "anshy8277@gmail.com",
      section: "B",
    },
    {
      serialNo: 76,
      alternateId: "22410100181",
      rollNo: "2K24CSUN01079",
      firstName: "ANSHIKA GARG",
      lastName: "OMPRAKASH",
      email: "anshigarg899@gmail.com",
      section: "B",
    },
    {
      serialNo: 77,
      alternateId: "22410100187",
      rollNo: "2K24CSUN01080",
      firstName: "ANSHU",
      lastName: "VIRENDER SINGH",
      email: "virenderrajput531@gmail.com",
      section: "B",
    },
    {
      serialNo: 80,
      alternateId: "22410100171",
      rollNo: "2K24CSUN01083",
      firstName: "AYUSHNA BORA",
      lastName: "HOSHIYAR SINGH BORA",
      email: "ayushna2006@gmail.com",
      section: "B",
    },
    {
      serialNo: 81,
      alternateId: "22410100114",
      rollNo: "2K24CSUN01085",
      firstName: "CHANDAN KUMAR",
      lastName: "DINESH KUMAR",
      email: "narayan.chandan2006@gmail.com",
      section: "B",
    },
    {
      serialNo: 82,
      alternateId: "22410100140",
      rollNo: "2K24CSUN01086",
      firstName: "CHARU AHUJA",
      lastName: "SANJAY AHUJA",
      email: "charuahuja012006@gmail.com",
      section: "B",
    },
    {
      serialNo: 83,
      alternateId: "224101001101",
      rollNo: "2K24CSUN01087",
      firstName: "DEBDEEP DEY",
      lastName: "SOMNATH DEY",
      email: "deydebdeep9@gmail.com",
      section: "B",
    },
    {
      serialNo: 85,
      alternateId: "22410100183",
      rollNo: "2K24CSUN01089",
      firstName: "DIGAJARLA JAYAPRAKASH",
      lastName: "DIGAJARLA SATHEESH",
      email: "jayaprakashdigajarla@gmail.com",
      section: "B",
    },
    {
      serialNo: 87,
      alternateId: "22410100137",
      rollNo: "2K24CSUN01091",
      firstName: "GARV JANGIR",
      lastName: "NEERAJ KUMAR",
      email: "garvsharma0033@gmail.com",
      section: "B",
    },
    {
      serialNo: 89,
      alternateId: "224101001188",
      rollNo: "2K24CSUN01093",
      firstName: "GOVVALA RITHESH",
      lastName: "GOVVALA DURGA PRASAD",
      email: "praveen200514@gmail.com",
      section: "B",
    },
    {
      serialNo: 90,
      alternateId: "224101001235",
      rollNo: "2K24CSUN01094",
      firstName: "GUNJAN TANEJA",
      lastName: "SURENDER",
      email: "gunjantaneja25@gmail.com",
      section: "B",
    },
    {
      serialNo: 91,
      alternateId: "22410100148",
      rollNo: "2K24CSUN01095",
      firstName: "HARSH KUMAR",
      lastName: "MANOJ KUMAR",
      email: "harshkumar.imfoo@gmail.com",
      section: "B",
    },
    {
      serialNo: 92,
      alternateId: "224101001140",
      rollNo: "2K24CSUN01096",
      firstName: "HARSHIT RAWAT",
      lastName: "SANJAY RAWAT",
      email: "rawatharshit685@gmail.com",
      section: "B",
    },
    {
      serialNo: 93,
      alternateId: "224101001107",
      rollNo: "2K24CSUN01097",
      firstName: "HIMANI SHARMA",
      lastName: "KRISHAN KANT SHARMA",
      email: "shimani.0205@gmail.com",
      section: "B",
    },
    {
      serialNo: 94,
      alternateId: "224101001133",
      rollNo: "2K24CSUN01098",
      firstName: "HNIN LAE KHAING",
      lastName: "THAN HTAY",
      email: "hlaekhine@gmail.com",
      section: "B",
    },
    {
      serialNo: 97,
      alternateId: "224101001191",
      rollNo: "2K24CSUN01101",
      firstName: "KARTIK BHATIA",
      lastName: "NAVNEET BHATIA",
      email: "kbhatia2606@gmail.com",
      section: "B",
    },
    {
      serialNo: 98,
      alternateId: "22410100915",
      rollNo: "2K24CSUN01102",
      firstName: "KRISH GARG",
      lastName: "PARMOD GARG",
      email: "krish.garg2708@gmail.com",
      section: "B",
    },
    {
      serialNo: 99,
      alternateId: "224101010N7",
      rollNo: "2K24CSUN01103",
      firstName: "KUMKUM KUMARI",
      lastName: "RANJIT KUMAR RAI",
      email: "kumarikamini436@gmail.com",
      section: "B",
    },
    {
      serialNo: 100,
      alternateId: "22410100184",
      rollNo: "2K24CSUN01104",
      firstName: "KUNJAL GARG",
      lastName: "BHUPENDER GARG",
      email: "kunjalgarg27@gmail.com",
      section: "B",
    },
    {
      serialNo: 101,
      alternateId: "22410100128",
      rollNo: "2K24CSUN01105",
      firstName: "LAKSHAY AGGARWAL",
      lastName: "TARUN AGARWAL",
      email: "aasthaaggarwal38@gmail.com",
      section: "B",
    },
    {
      serialNo: 102,
      alternateId: "224101001167",
      rollNo: "2K24CSUN01106",
      firstName: "LAKSHAY AGGARWAL",
      lastName: "RAMESH CHAND GUPTA",
      email: "laggarwal867@gmail.com",
      section: "B",
    },
    {
      serialNo: 103,
      alternateId: "22410100179",
      rollNo: "2K24CSUN01107",
      firstName: "LOVEDEEP SINGH",
      lastName: "NARENDRA SINGH ALMIYA",
      email: "lovedeepsingh2696@gmail.com",
      section: "B",
    },
    {
      serialNo: 104,
      alternateId: "224101001104",
      rollNo: "2K24CSUN01108",
      firstName: "MANAVJEET SINGH",
      lastName: "NARENDER SINGH",
      email: "manavtanwar0020@gmail.com",
      section: "B",
    },
    {
      serialNo: 105,
      alternateId: "2241010014",
      rollNo: "2K24CSUN01109",
      firstName: "MANDADI VINITH",
      lastName: "M. RANGARAO",
      email: "vinithmandadi2203995@gmail.com",
      section: "B",
    },
    {
      serialNo: 106,
      alternateId: "22410100185",
      rollNo: "2K24CSUN01110",
      firstName: "MEDA SRIHITHA",
      lastName: "MEDA MAHESHWAR REDDY",
      email: "medamaheshwar4@gmail.com",
      section: "B",
    },
    {
      serialNo: 107,
      alternateId: "22410100160",
      rollNo: "2K24CSUN01111",
      firstName: "MISHTI GUPTA",
      lastName: "VISHAL GUPTA",
      email: "mishtigupta@gmail.com",
      section: "B",
    },
    {
      serialNo: 108,
      alternateId: "224101001199",
      rollNo: "2K24CSUN01112",
      firstName: "MOULIK SHARMA",
      lastName: "RAJESH KUMAR SHARMA",
      email: "mouliksharma1810@gmail.com",
      section: "B",
    },
    {
      serialNo: 109,
      alternateId: "224101001166",
      rollNo: "2K24CSUN01113",
      firstName: "MRIDUL KUCHWAR",
      lastName: "MAHENDRA KUCHWAR",
      email: "mkuchwar@gmail.com",
      section: "B",
    },
    {
      serialNo: 110,
      alternateId: "224101001171",
      rollNo: "2K24CSUN01114",
      firstName: "NEHA SHARMA",
      lastName: "SUSHEEL KUMAR",
      email: "nehasharmaa8001@gmail.com",
      section: "B",
    },
    {
      serialNo: 111,
      alternateId: "224101001163",
      rollNo: "2K24CSUN01115",
      firstName: "NIKHIL PANDEY ARUN KUMAR",
      lastName: "RAJKISHOR PANDEY",
      email: "nikhil.prime12345@gmail.com",
      section: "B",
    },
    {
      serialNo: 112,
      alternateId: "22410100121",
      rollNo: "2K24CSUN01117",
      firstName: "NITIN SHARMA",
      lastName: "SUNIL KUMAR",
      email: "sunilkumarsharma81690@gmail.com",
      section: "B",
    },
    {
      serialNo: 113,
      alternateId: "22410100147",
      rollNo: "2K24CSUN01118",
      firstName: "PALLAVI TYAGI",
      lastName: "RAJNISH TYAGI",
      email: "abhaytyagi147@gmail.com",
      section: "B",
    },
    {
      serialNo: 114,
      alternateId: "22410100194",
      rollNo: "2K24CSUN01119",
      firstName: "PARI CHAUDHARY",
      lastName: "PRADEEP KUMAR",
      email: "parichaudhary007p@gmail.com",
      section: "B",
    },
    {
      serialNo: 115,
      alternateId: "224101001115",
      rollNo: "2K24CSUN01120",
      firstName: "PIYUSH ADLAKHA",
      lastName: "MAHESH ADLAKHA",
      email: "piyushady125@gmail.com",
      section: "B",
    },
    {
      serialNo: 116,
      alternateId: "22410100152",
      rollNo: "2K24CSUN01121",
      firstName: "PRABH DAYAL ARORA",
      lastName: "OM PRAKASH ARORA",
      email: "prabhdayal2005@gmail.com",
      section: "B",
    },
    {
      serialNo: 117,
      alternateId: "224101001160",
      rollNo: "2K24CSUN01122",
      firstName: "RAGHAV DIMRI",
      lastName: "RAJESH KUMAR DIMRI",
      email: "raghavdimri14@gmail.com",
      section: "B",
    },
    {
      serialNo: 118,
      alternateId: "22410100117",
      rollNo: "2K24CSUN01123",
      firstName: "RATHORE NAKUL BALVEER SINGH",
      lastName: "BALVEER SINGH RATHORE",
      email: "nakulrs98@gmail.com",
      section: "B",
    },
    {
      serialNo: 119,
      alternateId: "224101001195",
      rollNo: "2K24CSUN01124",
      firstName: "REEDIMA",
      lastName: "ANIL KUMAR",
      email: "reedimakathuria20@gmail.com",
      section: "B",
    },
    {
      serialNo: 120,
      alternateId: "22410100166",
      rollNo: "2K24CSUN01125",
      firstName: "RIDDHIMA YADAV",
      lastName: "KAMAL KISHORE YADAV",
      email: "riddhima01052007@gmail.com",
      section: "B",
    },
    {
      serialNo: 122,
      alternateId: "224101001180",
      rollNo: "2K24CSUN01127",
      firstName: "ROUNAK SINGH RAWAT",
      lastName: "MEHAR SINGH",
      email: "rounakrawat52@gmail.com",
      section: "B",
    },
    {
      serialNo: 123,
      alternateId: "22410100115",
      rollNo: "2K24CSUN01128",
      firstName: "RUPAK BHARDWAJ",
      lastName: "SATPAL BHARDWAJ",
      email: "rupakbhardwaj07@gmail.com",
      section: "B",
    },
    {
      serialNo: 124,
      alternateId: "224101001159",
      rollNo: "2K24CSUN01129",
      firstName: "RUPANSH DUBEY",
      lastName: "UMA KANT DUBEY",
      email: "rupanshdubey1218@gmail.com",
      section: "B",
    },
    {
      serialNo: 125,
      alternateId: "22410100198",
      rollNo: "2K24CSUN01130",
      firstName: "SANJANA SINGH",
      lastName: "SANJIV KUMAR",
      email: "sanjanasingh142005@gmail.com",
      section: "B",
    },
    {
      serialNo: 126,
      alternateId: "22410100175",
      rollNo: "2K24CSUN01131",
      firstName: "SANJU",
      lastName: "SURENDER SINGH",
      email: "itssanju352@gmail.com",
      section: "B",
    },
    {
      serialNo: 127,
      alternateId: "224101001204",
      rollNo: "2K24CSUN01132",
      firstName: "SHIVAM JHA",
      lastName: "SANJAY JHA",
      email: "jhashiv2324@gmail.com",
      section: "B",
    },
    {
      serialNo: 128,
      alternateId: "22410100178",
      rollNo: "2K24CSUN01133",
      firstName: "SHUBHAM JOSHI",
      lastName: "BHARTENDU JOSHI",
      email: "joshishubham1306@gmail.com",
      section: "B",
    },
    {
      serialNo: 129,
      alternateId: "22410100193",
      rollNo: "2K24CSUN01134",
      firstName: "SNEHA RAWAT",
      lastName: "KULDEEP SINGH",
      email: "rawatsneha2209@gmail.com",
      section: "B",
    },
    {
      serialNo: 130,
      alternateId: "224101001155",
      rollNo: "2K24CSUN01135",
      firstName: "SRIRANGAM MANOBHIRAM",
      lastName: "SRIRANGAM NARASIMHA RAO",
      email: "srirangammanobhiram@gmail.com",
      section: "B",
    },
    {
      serialNo: 131,
      alternateId: "224101001158",
      rollNo: "2K24CSUN01136",
      firstName: "TANMAY SHARMA",
      lastName: "AKHIL SHARMA",
      email: "ts2851181@gmail.com",
      section: "B",
    },
    {
      serialNo: 133,
      alternateId: "224101001196",
      rollNo: "2K24CSUN01138",
      firstName: "VARUN GUPTA",
      lastName: "DHARMENDRA KUMAR GUPTA",
      email: "varungupta0701@gmail.com",
      section: "B",
    },
    {
      serialNo: 134,
      alternateId: "22410100129",
      rollNo: "2K24CSUN01139",
      firstName: "VINAY SINGH",
      lastName: "GAJENDER SINGH",
      email: "gajender79singh@gmail.com",
      section: "B",
    },
    {
      serialNo: 135,
      alternateId: "224101001117",
      rollNo: "2K24CSUN01140",
      firstName: "VISHNU SINGH",
      lastName: "KISHUN SINGH",
      email: "vishnusinghrajput18@gmail.com",
      section: "B",
    },
    {
      serialNo: 136,
      alternateId: "224101001183",
      rollNo: "2K24CSUN01141",
      firstName: "VIVEK SINGH DAGAR",
      lastName: "CHANDAN SINGH DAGAR",
      email: "vivekdagar2006@gmail.com",
      section: "B",
    },
    {
      serialNo: 137,
      alternateId: "224101001200",
      rollNo: "2K24CSUN01142",
      firstName: "YASHODA THAPA",
      lastName: "SURENDRA THAPA",
      email: "st101176@gmail.com",
      section: "B",
    },
    {
      serialNo: 212,
      alternateId: "225301001004",
      rollNo: "2K25CSUM01002",
      firstName: "MEDHA MOHILEY",
      lastName: "NEERAJ MOHILEY",
      email: "mmohiley29@yahoo.com",
      section: "B",
    },
  ];
  await seedStudents(sectionBConfig, studentsB);

  // --- Section C Configuration and Data ---
  const sectionCConfig: SectionConfig = {
    programCode: "CSE",
    programName: "Computer Science and Engineering",
    sectionName: "C",
    semester: 3,
    batchYear: 2024,
  };
  const studentsC: StudentData[] = [
    {
      serialNo: 138,
      alternateId: "22410100189",
      rollNo: "2K24CSUN01143",
      firstName: "AAKASH KOTHARI",
      lastName: "SURESH KOTHARI",
      email: "kothariakash2007031@gmail.com",
      section: "C",
    },
    {
      serialNo: 139,
      alternateId: "22410100130",
      rollNo: "2K24CSUN01144",
      firstName: "ABHISHEK BORA",
      lastName: "INDRAJIT BORA",
      email: "indrajitbora80@gmail.com",
      section: "C",
    },
    {
      serialNo: 140,
      alternateId: "22410100192",
      rollNo: "2K24CSUN01145",
      firstName: "ABHISHEK SHARMA",
      lastName: "ANIL KUMAR",
      email: "jangidabhishek723@gmail.com",
      section: "C",
    },
    {
      serialNo: 141,
      alternateId: "22410100190",
      rollNo: "2K24CSUN01146",
      firstName: "ADITYA CHOUDHARY",
      lastName: "PREM SINGH CHOUDHARY",
      email: "adityachoudhary997755@gmail.com",
      section: "C",
    },
    {
      serialNo: 143,
      alternateId: "224101001203",
      rollNo: "2K24CSUN01148",
      firstName: "AKASH YADAV",
      lastName: "RAKESH YADAV",
      email: "akashahir60@gmail.com",
      section: "C",
    },
    {
      serialNo: 144,
      alternateId: "2241010019",
      rollNo: "2K24CSUN01151",
      firstName: "ANSH TYAGI",
      lastName: "RAJEEV KUMAR",
      email: "anshtyagi2024@gmail.com",
      section: "C",
    },
    {
      serialNo: 145,
      alternateId: "224101016N0",
      rollNo: "2K24CSUN01152",
      firstName: "AVISHI GUPTA",
      lastName: "GAURAV GUPTA",
      email: "avishi9@gmail.com",
      section: "C",
    },
    {
      serialNo: 146,
      alternateId: "224101001136",
      rollNo: "2K24CSUN01153",
      firstName: "AYAAN ANWAR",
      lastName: "JAWED ANWAR",
      email: "kolayaanu@gmail.com",
      section: "C",
    },
    {
      serialNo: 147,
      alternateId: "224101001112",
      rollNo: "2K24CSUN01154",
      firstName: "BHOOMI SHARMA",
      lastName: "DINESH KUMAR",
      email: "bhoomisharma3009@gmail.com",
      section: "C",
    },
    {
      serialNo: 148,
      alternateId: "224101001193",
      rollNo: "2K24CSUN01156",
      firstName: "GADERU KRISHNA NANDA",
      lastName: "G CHINNA MALLAIAH",
      email: "krishnananda644@gmail.com",
      section: "C",
    },
    {
      serialNo: 149,
      alternateId: "224101001152",
      rollNo: "2K24CSUN01157",
      firstName: "HARIOM JHA",
      lastName: "SHAMBHU NATH JHA",
      email: "jhahariom855@gmail.com",
      section: "C",
    },
    {
      serialNo: 152,
      alternateId: "22410100127",
      rollNo: "2K24CSUN01160",
      firstName: "HARSHIT RAJ",
      lastName: "NAGENDRA KUMAR",
      email: "harshitraj2005@gmail.com",
      section: "C",
    },
    {
      serialNo: 153,
      alternateId: "224101001113",
      rollNo: "2K24CSUN01161",
      firstName: "HARSHIT SINGHAL",
      lastName: "LOKESH KUMAR",
      email: "singlaharshit1103@outlook.com",
      section: "C",
    },
    {
      serialNo: 155,
      alternateId: "224101001178",
      rollNo: "2K24CSUN01163",
      firstName: "HUNNY KAUSHIK",
      lastName: "VIKRAM",
      email: "hunnykaushik363@gmail.com",
      section: "C",
    },
    {
      serialNo: 157,
      alternateId: "22410100153",
      rollNo: "2K24CSUN01165",
      firstName: "ISHITA BABBAR",
      lastName: "NEERAJ BABBAR",
      email: "ishitababbar28@gmail.com",
      section: "C",
    },
    {
      serialNo: 159,
      alternateId: "22410100180",
      rollNo: "2K24CSUN01167",
      firstName: "JAPLEEN KAUR",
      lastName: "AMIT SINGH",
      email: "kjapleen42@gmail.com",
      section: "C",
    },
    {
      serialNo: 160,
      alternateId: "224101001138",
      rollNo: "2K24CSUN01168",
      firstName: "JASMINE KAUR",
      lastName: "PRABHJIT SINGH",
      email: "prabhjitsingh74@gmail.com",
      section: "C",
    },
    {
      serialNo: 161,
      alternateId: "22410100164",
      rollNo: "2K24CSUN01169",
      firstName: "JATIN CHHABRA",
      lastName: "MANOJ KUMAR CHHABRA",
      email: "jatinchhabra681@gmail.com",
      section: "C",
    },
    {
      serialNo: 162,
      alternateId: "224101001114",
      rollNo: "2K24CSUN01170",
      firstName: "JATIN SINGHAL",
      lastName: "MAHESH CHAND",
      email: "jatinsinghal183@gmail.com",
      section: "C",
    },
    {
      serialNo: 164,
      alternateId: "22410100126",
      rollNo: "2K24CSUN01172",
      firstName: "KAVY KHANNA",
      lastName: "RAJESH KHANNA",
      email: "kavykhanna08@gmail.com",
      section: "C",
    },
    {
      serialNo: 166,
      alternateId: "224101001165",
      rollNo: "2K24CSUN01174",
      firstName: "KHUSHI VATS",
      lastName: "DAVINDER SHARMA",
      email: "khushivats0201@gmail.com",
      section: "C",
    },
    {
      serialNo: 167,
      alternateId: "224101001137",
      rollNo: "2K24CSUN01175",
      firstName: "KIRTI SINGHAL",
      lastName: "VIVEK KUMAR SINGHAL",
      email: "kirtisinghal049@gmail.com",
      section: "C",
    },
    {
      serialNo: 169,
      alternateId: "22410100162",
      rollNo: "2K24CSUN01177",
      firstName: "KRISHNA KHANNA",
      lastName: "VIJAY KUMAR KHANNA",
      email: "krishnakhanna155@gmail.com",
      section: "C",
    },
    {
      serialNo: 170,
      alternateId: "22410100168",
      rollNo: "2K24CSUN01178",
      firstName: "KUNAL SHARMA",
      lastName: "UMADUTT SHARMA",
      email: "kunalssharma125@gmail.com",
      section: "C",
    },
    {
      serialNo: 171,
      alternateId: "2241010018",
      rollNo: "2K24CSUN01179",
      firstName: "MINTU",
      lastName: "RAJVEER",
      email: "mintuchandila72@gmail.com",
      section: "C",
    },
    {
      serialNo: 172,
      alternateId: "22410100146",
      rollNo: "2K24CSUN01180",
      firstName: "NAMPELLY AKSHAY",
      lastName: "NAMPELLY LAXMAN",
      email: "akshaynampelly1@gmail.com",
      section: "C",
    },
    {
      serialNo: 173,
      alternateId: "224101017N5",
      rollNo: "2K24CSUN01181",
      firstName: "NARLA VAMSHI",
      lastName: "NARLA VENKATAIAH",
      email: "narlavamshi799@gmail.com",
      section: "C",
    },
    {
      serialNo: 174,
      alternateId: "224101001106",
      rollNo: "2K24CSUN01182",
      firstName: "NAVEEN JINDAL",
      lastName: "BHAGWATI PARSAD",
      email: "naveen0311005@gmail.com",
      section: "C",
    },
    {
      serialNo: 175,
      alternateId: "22410100111",
      rollNo: "2K24CSUN01183",
      firstName: "NIRBHAY",
      lastName: "HARI RAM",
      email: "rhari1132@gmail.com",
      section: "C",
    },
    {
      serialNo: 176,
      alternateId: "22410100967",
      rollNo: "2K24CSUN01185",
      firstName: "PENDLI JASHVANTH MANIKANTA",
      lastName: "PENDLI SRINIVASA RAO",
      email: "jashvanthmanikanta384@gmail.com",
      section: "C",
    },
    {
      serialNo: 177,
      alternateId: "22410100196",
      rollNo: "2K24CSUN01186",
      firstName: "PIYUSH JUNEJA",
      lastName: "MAHENDER PAL JUNEJA",
      email: "piyushjuneja905@gmail.com",
      section: "C",
    },
    {
      serialNo: 178,
      alternateId: "22410100177",
      rollNo: "2K24CSUN01187",
      firstName: "PIYUSH KUMAR SHARMA",
      lastName: "ROOPENDRA KUMAR",
      email: "ipiyushsharma24@gmail.com",
      section: "C",
    },
    {
      serialNo: 179,
      alternateId: "22410100125",
      rollNo: "2K24CSUN01188",
      firstName: "PRABHLEEN KAUR",
      lastName: "KAVEER SINGH MANDLA",
      email: "prabh.june@gmail.com",
      section: "C",
    },
    {
      serialNo: 182,
      alternateId: "224101001131",
      rollNo: "2K24CSUN01191",
      firstName: "PRINCE SHARMA",
      lastName: "VIJAY PAL",
      email: "ps415117@gmail.com",
      section: "C",
    },
    {
      serialNo: 183,
      alternateId: "224101001118",
      rollNo: "2K24CSUN01192",
      firstName: "PUJARI SHIVA KUMAR",
      lastName: "PUJARI SWAMY",
      email: "pujarishiva654@gmail.com",
      section: "C",
    },
    {
      serialNo: 185,
      alternateId: "224101001182",
      rollNo: "2K24CSUN01194",
      firstName: "RAJA BABU RAI",
      lastName: "JAGDEV RAI",
      email: "rair69691@gmail.com",
      section: "C",
    },
    {
      serialNo: 186,
      alternateId: "224101001148",
      rollNo: "2K24CSUN01195",
      firstName: "ROHAN",
      lastName: "MAHIPAL SINGH",
      email: "singh.mahipal1982@gmail.com",
      section: "C",
    },
    {
      serialNo: 187,
      alternateId: "22410100124",
      rollNo: "2K24CSUN01196",
      firstName: "ROHAN SHARMA",
      lastName: "MANOJ SHARMA",
      email: "rohansharma3021@gmail.com",
      section: "C",
    },
    {
      serialNo: 189,
      alternateId: "224101001132",
      rollNo: "2K24CSUN01198",
      firstName: "SAGAR KUMAR",
      lastName: "JITENDRA PRASAD",
      email: "sagar8789297230kumar@gmail.com",
      section: "C",
    },
    {
      serialNo: 190,
      alternateId: "22410100191",
      rollNo: "2K24CSUN01199",
      firstName: "SARTHAK MITTAL",
      lastName: "RAJNEESH MITTAL",
      email: "mittalsarthak102@gmail.com",
      section: "C",
    },
    {
      serialNo: 191,
      alternateId: "224101001141",
      rollNo: "2K24CSUN01200",
      firstName: "SHAMBHAVI",
      lastName: "KRISHNA KUMAR",
      email: "shambhavi.dpsg@gmail.com",
      section: "C",
    },
    {
      serialNo: 192,
      alternateId: "22410100143",
      rollNo: "2K24CSUN01201",
      firstName: "SHENIGARAM MANISH",
      lastName: "SHENIGARAM SRIDHAR",
      email: "sridharreddy.klsm@gmail.com",
      section: "C",
    },
    {
      serialNo: 193,
      alternateId: "224101001149",
      rollNo: "2K24CSUN01202",
      firstName: "SHINU SURA",
      lastName: "RAJBIR",
      email: "shinusura0163@gmail.com",
      section: "C",
    },
    {
      serialNo: 194,
      alternateId: "22410100156",
      rollNo: "2K24CSUN01203",
      firstName: "SONAKSHI CHAND",
      lastName: "GAJENDRA MOHAN CHAND",
      email: "sonakshichand10@gmail.com",
      section: "C",
    },
    {
      serialNo: 195,
      alternateId: "224101001187",
      rollNo: "2K24CSUN01204",
      firstName: "TANISHA",
      lastName: "PAWAN KUMAR ROHILLA",
      email: "pawanrohilla37971@gmail.com",
      section: "C",
    },
    {
      serialNo: 196,
      alternateId: "224101001100",
      rollNo: "2K24CSUN01205",
      firstName: "TANYA",
      lastName: "RATHORE",
      email: "rathoretanya76@gmail.com",
      section: "C",
    },
    {
      serialNo: 197,
      alternateId: "224101001119",
      rollNo: "2K24CSUN01206",
      firstName: "VANSH PRATAP",
      lastName: "MANOHAR SINGH",
      email: "vanshpratap9540999403@gmail.com",
      section: "C",
    },
    {
      serialNo: 198,
      alternateId: "224101001126",
      rollNo: "2K24CSUN01207",
      firstName: "VATSAL GOEL",
      lastName: "AJAY KUMAR GOEL",
      email: "vatsalgoel13@gmail.com",
      section: "C",
    },
    {
      serialNo: 199,
      alternateId: "224101001164",
      rollNo: "2K24CSUN01208",
      firstName: "VENKATA RAMANA REDDY KASIREDDY",
      lastName: "SRINIVAS REDDY",
      email: "venkatramana8281@gamil.com",
      section: "C",
    },
    {
      serialNo: 200,
      alternateId: "22410100157",
      rollNo: "2K24CSUN01209",
      firstName: "VIDIT CHAUHAN",
      lastName: "RANDHIR",
      email: "viditchauhan19@gmail.com",
      section: "C",
    },
    {
      serialNo: 202,
      alternateId: "224101001150",
      rollNo: "2K24CSUN01211",
      firstName: "YANIS HASAN KHAN",
      lastName: "TARIQ HASAN KHAN",
      email: "yanishasankhan@gmail.com",
      section: "C",
    },
    {
      serialNo: 203,
      alternateId: "224101001125",
      rollNo: "2K24CSUN01212",
      firstName: "YASHVEER TANWAR",
      lastName: "SURENDER TANWAR",
      email: "tanwaryashveer08@gmail.com",
      section: "C",
    },
    {
      serialNo: 204,
      alternateId: "2241010015",
      rollNo: "2K24CSUN01213",
      firstName: "YUVRAJ NAGAR",
      lastName: "PRATAPVEER",
      email: "nagaryuvraj04@gmail.com",
      section: "C",
    },
    {
      serialNo: 209,
      alternateId: "22501001L026",
      rollNo: "2K25CSUL01008",
      firstName: "NAMAN TYAGI",
      lastName: "JITENDER KUMAR",
      email: "namantyagi385@gmail.com",
      section: "C",
    },
    {
      serialNo: 210,
      alternateId: "22501001L027",
      rollNo: "2K25CSUL01010",
      firstName: "AAKASH",
      lastName: "BIRENDER",
      email: "dagaraakash94@gmail.com",
      section: "C",
    },
  ];
  await seedStudents(sectionCConfig, studentsC);

  // --- Section D Configuration and Data ---
  const sectionDConfig: SectionConfig = {
    programCode: "CSE",
    programName: "Computer Science and Engineering",
    sectionName: "D",
    semester: 3,
    batchYear: 2024,
  };
  const studentsD: StudentData[] = [
    {
      serialNo: 4,
      alternateId: "224101001184",
      rollNo: "2K24CSUN01005",
      firstName: "AKSHIT SINGH",
      lastName: "TARUN SINGH",
      email: "friendstraders2004@yahoo.co.in",
      section: "D",
    },
    {
      serialNo: 5,
      alternateId: "224101001227",
      rollNo: "2K24CSUN01006",
      firstName: "AMAN KUMAR RAI",
      lastName: "SUNIL KUMAR ROY",
      email: "amanrai9660@gmail.com",
      section: "D",
    },
    {
      serialNo: 18,
      alternateId: "22410100158",
      rollNo: "2K24CSUN01018",
      firstName: "DEEPANSHU DAHIYA",
      lastName: "RAMESH DAHIYA",
      email: "deepanshudahiya640@gmail.com",
      section: "D",
    },
    {
      serialNo: 28,
      alternateId: "224101001231",
      rollNo: "2K24CSUN01029",
      firstName: "HITESH KUMAR ROHELA",
      lastName: "ASHOK KUMAR",
      email: "hiteshkr637@gmail.com",
      section: "D",
    },
    {
      serialNo: 34,
      alternateId: "224101001197",
      rollNo: "2K24CSUN01035",
      firstName: "KHUSHI YADAV",
      lastName: "MUNNA YADAV",
      email: "yadavkhushnoor@gmail.com",
      section: "D",
    },
    {
      serialNo: 35,
      alternateId: "224101001198",
      rollNo: "2K24CSUN01036",
      firstName: "KISALAY JHA",
      lastName: "NAGESH NATH JHA",
      email: "kisalayjha01@gmail.com",
      section: "D",
    },
    {
      serialNo: 46,
      alternateId: "224101001232",
      rollNo: "2K24CSUN01047",
      firstName: "NISHANT KUMAR",
      lastName: "BHOLA SHARMA",
      email: "nk1483863@gmail.com",
      section: "D",
    },
    {
      serialNo: 48,
      alternateId: "224101001185",
      rollNo: "2K24CSUN01049",
      firstName: "OMPRAKASH TRIVENI RAI",
      lastName: "TRIVENI RAI",
      email: "royom4@gmail.com",
      section: "D",
    },
    {
      serialNo: 50,
      alternateId: "224101001211",
      rollNo: "2K24CSUN01051",
      firstName: "PODIRLA ROHIT RAMARAO",
      lastName: "LATE",
      email: "podirlarohit2006@gmail.com",
      section: "D",
    },
    {
      serialNo: 53,
      alternateId: "224101001222",
      rollNo: "2K24CSUN01054",
      firstName: "PRINCE",
      lastName: "LOVEKUSH",
      email: "deshwalprince699@gmail.com",
      section: "D",
    },
    {
      serialNo: 62,
      alternateId: "224101001144",
      rollNo: "2K24CSUN01064",
      firstName: "SHOURYA SINGH",
      lastName: "RAJEEV SINGH",
      email: "mrshouryathakur2007@gmail.com",
      section: "D",
    },
    {
      serialNo: 65,
      alternateId: "224101001233",
      rollNo: "2K24CSUN01067",
      firstName: "VANSH BHATIA",
      lastName: "LALIT BHATIA",
      email: "vansh.bhatia3540@gmail.com",
      section: "D",
    },
    {
      serialNo: 66,
      alternateId: "224101001145",
      rollNo: "2K24CSUN01068",
      firstName: "VANSH BIDHURI",
      lastName: "SANJAY BIDHURI",
      email: "vanshbidhuri2004@gmail.com",
      section: "D",
    },
    {
      serialNo: 68,
      alternateId: "224101001209",
      rollNo: "2K24CSUN01070",
      firstName: "VISHESH SINGH BISHT",
      lastName: "DEVENDRA SINGH BISHT",
      email: "visheshbisht456@gmail.com",
      section: "D",
    },
    {
      serialNo: 71,
      alternateId: "224101001210",
      rollNo: "2K24CSUN01073",
      firstName: "ABHINAV SINGH",
      lastName: "SUDHIR KUMAR SINGH",
      email: "abhinavsingh6867@gmail.com",
      section: "D",
    },
    {
      serialNo: 72,
      alternateId: "224101001175",
      rollNo: "2K24CSUN01074",
      firstName: "ADITYA SATYARTHI",
      lastName: "D P SATYARTHI",
      email: "aditya.satyarthi06@gmail.com",
      section: "D",
    },
    {
      serialNo: 74,
      alternateId: "224101001218",
      rollNo: "2K24CSUN01077",
      firstName: "ANKIT PANDEY",
      lastName: "TAPAN KUMAR PANDEY",
      email: "ankitraj456153@gmail.com",
      section: "D",
    },
    {
      serialNo: 78,
      alternateId: "224101001169",
      rollNo: "2K24CSUN01081",
      firstName: "ARNIT MISHRA",
      lastName: "RAJ PRIYA GOPAL MISHRA",
      email: "iamarnitrmishra@gmail.com",
      section: "D",
    },
    {
      serialNo: 79,
      alternateId: "224101001228",
      rollNo: "2K24CSUN01082",
      firstName: "ARYAN",
      lastName: "PREMVEER SINGH",
      email: "manju.mca.05@gmail.com",
      section: "D",
    },
    {
      serialNo: 84,
      alternateId: "224101001201",
      rollNo: "2K24CSUN01088",
      firstName: "DEVANSH BHARDWAJ",
      lastName: "RAMAKANT SHARMA",
      email: "ramakant-9@hotmail.com",
      section: "D",
    },
    {
      serialNo: 86,
      alternateId: "224101001217",
      rollNo: "2K24CSUN01090",
      firstName: "FARHAN FARHAT",
      lastName: "MD SOHAIL",
      email: "farhanfarhat123@gmail.com",
      section: "D",
    },
    {
      serialNo: 88,
      alternateId: "224101001225",
      rollNo: "2K24CSUN01092",
      firstName: "GARVEET SINGH",
      lastName: "SATYA VEER SINGH",
      email: "garvit1223@gmail.com",
      section: "D",
    },
    {
      serialNo: 95,
      alternateId: "224101001226",
      rollNo: "2K24CSUN01099",
      firstName: "JATIN VIRMANI",
      lastName: "CHANDER SHEKHAR VIRMANI",
      email: "jatinvirmani269@gmail.com",
      section: "D",
    },
    {
      serialNo: 96,
      alternateId: "224101001220",
      rollNo: "2K24CSUN01100",
      firstName: "JATIN YADAV",
      lastName: "TARUN KUMAR",
      email: "jatinyadav1251@gmail.com",
      section: "D",
    },
    {
      serialNo: 121,
      alternateId: "224101001229",
      rollNo: "2K24CSUN01126",
      firstName: "RIDHI ARORA",
      lastName: "SACHIN ARORA",
      email: "ridsarora16@gmail.com",
      section: "D",
    },
    {
      serialNo: 132,
      alternateId: "224101001181",
      rollNo: "2K24CSUN01137",
      firstName: "VAIBHAV MALIK",
      lastName: "DEVASISH MALIK",
      email: "vaibhavmalik6.vm@gmail.com",
      section: "D",
    },
    {
      serialNo: 142,
      alternateId: "224101001206",
      rollNo: "2K24CSUN01147",
      firstName: "AKANKSHA AGRAWAL",
      lastName: "SHYAM SUNDER AGRAWAL",
      email: "shyamsunderagrawal906@gmail.com",
      section: "D",
    },
    {
      serialNo: 150,
      alternateId: "2241010125",
      rollNo: "2K24CSUN01158",
      firstName: "HARSH RANDHIR SINGH",
      lastName: "RANDHIR SINGH",
      email: "harshgi200@gmail.com",
      section: "D",
    },
    {
      serialNo: 151,
      alternateId: "224101001224",
      rollNo: "2K24CSUN01159",
      firstName: "HARSH VARDHAN SINGH",
      lastName: "SATYA JEET SINGH",
      email: "harshvs222@gmail.com",
      section: "D",
    },
    {
      serialNo: 154,
      alternateId: "224101001214",
      rollNo: "2K24CSUN01162",
      firstName: "HIMESH SHARMA",
      lastName: "SANJEEV SHARMA",
      email: "kamleshsharma13011980@gmail.com",
      section: "D",
    },
    {
      serialNo: 156,
      alternateId: "224101001102",
      rollNo: "2K24CSUN01164",
      firstName: "ISHANK",
      lastName: "SATISH KUMAR ROHILLA",
      email: "rohillaishank7@gmail.com",
      section: "D",
    },
    {
      serialNo: 158,
      alternateId: "224101001110",
      rollNo: "2K24CSUN01166",
      firstName: "JAI KISHAN JHA",
      lastName: "JAGANNATH JHA",
      email: "jnjha51@gmail.com",
      section: "D",
    },
    {
      serialNo: 163,
      alternateId: "22410101215",
      rollNo: "2K24CSUN01171",
      firstName: "JOY PRASAD",
      lastName: "BHAGWATI PRASAD",
      email: "mehrasakshi828@gmail.com",
      section: "D",
    },
    {
      serialNo: 165,
      alternateId: "22410100960",
      rollNo: "2K24CSUN01173",
      firstName: "KHUSHI RATHI",
      lastName: "NARENDER",
      email: "garimaguddi83@gmail.com",
      section: "D",
    },
    {
      serialNo: 168,
      alternateId: "224101018N5",
      rollNo: "2K24CSUN01176",
      firstName: "KRIPA POPLI",
      lastName: "PRAVIN POPLI",
      email: "kripapopli@gmail.com",
      section: "D",
    },
    {
      serialNo: 180,
      alternateId: "224101001230",
      rollNo: "2K24CSUN01189",
      firstName: "PRAHALAD SAH TELI",
      lastName: "BHUTUN SA TELI",
      email: "sahprahalad754@gmail.com",
      section: "D",
    },
    {
      serialNo: 181,
      alternateId: "2241010122",
      rollNo: "2K24CSUN01190",
      firstName: "PRASHANT",
      lastName: "OMBIR SINGH",
      email: "prashantdinday07@gmail.com",
      section: "D",
    },
    {
      serialNo: 184,
      alternateId: "224101001223",
      rollNo: "2K24CSUN01193",
      firstName: "RAHUL SINGH",
      lastName: "JASWANT SINGH",
      email: "rahul54.singhrathore@gmail.com",
      section: "D",
    },
    {
      serialNo: 188,
      alternateId: "224101001202",
      rollNo: "2K24CSUN01197",
      firstName: "RUDRA PRATAP KAUL",
      lastName: "AJAY KAUL",
      email: "kaulaja@gmail.com",
      section: "D",
    },
    {
      serialNo: 201,
      alternateId: "224101001190",
      rollNo: "2K24CSUN01210",
      firstName: "VISHWAS AHUJA",
      lastName: "HARISH AHUJA",
      email: "vishwasahuja62@gmail.com",
      section: "D",
    },
    {
      serialNo: 205,
      alternateId: "224101001237",
      rollNo: "2K24CSUN01214",
      firstName: "ARYAN KUMAR",
      lastName: "DHARMENDRA KUMAR PASWAN",
      email: "aryankumar870975@gmail.com",
      section: "D",
    },
    {
      serialNo: 206,
      alternateId: "224101001234",
      rollNo: "2K24CSUN01215",
      firstName: "RAUNAK KUMAR",
      lastName: "DHARMENDRA KUMAR PASWAN",
      email: "raunakkumarbtps@gmail.com",
      section: "D",
    },
    {
      serialNo: 207,
      alternateId: "225301001003",
      rollNo: "2K25CSUL01003",
      firstName: "BHARAT",
      lastName: "RAJINDER",
      email: "vishalkain2005@gmail.com",
      section: "D",
    },
  ];
  await seedStudents(sectionDConfig, studentsD);

  console.log("\n✅ All student seeding tasks completed successfully!\n");
}

main()
  .catch((e) => {
    console.error("❌ Error seeding students:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
